name: Build ADS1115 Chip

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
     
      - name: Clean previous WASM
        run: rm -f *.wasm

      - name: Debug before build
        run: |
          echo "== Before build =="
          ls -R .

      - name: Build chip
        uses: wokwi/wokwi-chip-clang-action@main
        with:
          sources: src/main.c

      # Corrija as permiss√µes da pasta dist inteira
      - name: Fix dist folder and files ownership
        run: sudo chown -R runner:runner dist

      - name: Copy chip.json and chip.svg
        run: |
          cp chip.json dist/chip.json
          cp chip.svg dist/chip.svg

      - name: Check dist content and permissions
        run: ls -l dist/

      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: chip
          path: |
            dist/chip.svg
            dist/chip.json
            dist/chip.wasm
          retention-days: 7

  release:
    name: Release
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download compiled chip
        uses: actions/download-artifact@v4
        with:
          name: chip
          path: chip

      - name: Create a zip archive
        run: cd chip && zip -9 ../chip.zip chip.*
        env:
          ZIP_VERSION: ${{ github.ref_name }}

      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: chip.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true